### ISSUE TITLE
Temperature example discrepancy

### ISSUE THREAD

**Issue by dhylands** [moziot/wot#28]
In the [Thing resource](https://moziot.github.io/wot/#thing-resource) it shows temperature as an integer.
In the [Property resource](https://moziot.github.io/wot/#property-resource) response for retrieving the temperature it shows the temperature as a string (i.e. 21 in quotes) rather than an integer (21 with no quotes).

**Comment by benfrancis** [comment]
Fixed by https://github.com/moziot/wot/commit/b8dff383dfc8dea3eaf59e7899c0c50f0ab3bc9a
