### ISSUE TITLE
Change properties from array to object

### ISSUE THREAD

**Issue by benfrancis** [moziot/wot#31]
After having looked at lots of prior art, I think we should consider changing the properties member into an object rather than an array, with the property name as a key.

For example this...

```
  "properties": [
    {
      "name": "temperature",
      "type": "number",
      "unit": "celsius",
      "description": "An ambient temperature sensor",
      "href": "/things/pi/properties/temperature"
    },
    {
      "name": "humidity",
      "type": "number",
      "unit": "percent",
      "href": "/things/pi/properties/humidity"
    },
    {
      "name": "led",
      "type": "boolean",
      "description": "A red LED",
      "href": "/things/pi/properties/led"
    }
  ]
```

would become this...

```
  "properties": {
    "temperature" {
      "type": "number",
      "unit": "celsius",
      "description": "An ambient temperature sensor",
      "href": "/things/pi/properties/temperature"
    },
   "humidity": {
      "type": "number",
      "unit": "percent",
      "href": "/things/pi/properties/humidity"
    },
    "led": {
      "type": "boolean",
      "description": "A red LED",
      "href": "/things/pi/properties/led"
    }
  }
```

Reasons:
* A particular property can be more directly referenced in code (e.g. using a JSON pointer) without having to iterate through the array
* The "name" member of a property object could still be used as a human friendly name (This is what "name" is used for elsewhere in the spec), while the key is used as a computer friendly string to reference the property by
* Lots of existing systems like JSON Schema and cloud services like AWS IoT & Azure IoT do it this way

We should also consider making the same change to actions and properties in the Thing Description.

**Comment by benfrancis** [comment]
@dhylands Heads up that if made, this change would affect code already written for our gateway implementation.

**Comment by dhylands** [comment]
@benfrancis I'm all for it. I think that the changes would be pretty minimal, but I won't know for sure until I try it.

**Comment by benfrancis** [comment]
Fixed by https://github.com/moziot/wot/commit/b8dff383dfc8dea3eaf59e7899c0c50f0ab3bc9a
